### PR TITLE
Users can have custom public and private metadata

### PR DESCRIPTION
**Pull request by alex-ntousias**
## Type of change

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] 🌟 New feature (non-breaking change which adds functionality)
- [ ] 🔨 Breaking change (fix or feature that would cause existing functionality)
- [ ] 📖 Docs change / refactoring / dependency upgrade to change)

## Description

When updating a user, you can optionally define public and private metadata.
This metadata are JSON objects of any form and will be stored and returned along with the user itself.

### Related Issue (optional)

https://www.notion.so/clerkdev/User-custom-attributes-29dc3bba4d9442849c9831a09089042c

### CODE REVIEW

**Review by braden-clerk — APPROVED** [review]
Other than the failing test, this looks good 👍

**Comment by alex-ntousias** [comment]
@braden-clerk Yes, the failing test is because we haven't merged the `clerk_go` relevant changes yet. Basically the integration is failing, which is a good thing 😉

**Comment by braden-clerk** [comment]
very cool :)

**Comment by braden-clerk** [comment]
I guess we need to update the node-sdk with this as well... man what a pain already... w/ only two SDKs 😞

**Comment by alex-ntousias** [comment]
@braden-clerk Yes, already have the changes here: https://github.com/clerkinc/clerk-sdk-node/pull/10
But yes, maybe we should revisit the SDK generation solution again. It will be really painful once we add more.

**Review by agis — APPROVED** [review]

**Pull request merged**
